version: "3.9"
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: omni
      POSTGRES_PASSWORD: omni
      POSTGRES_DB: omniagentos
    ports:
      - "5432:5432"
